spring:
  security:
    user:
      name: admin
      password: admin123
  main:
    web-application-type: reactive

  datasource:
    url: jdbc:postgresql://localhost:5432/apigateway
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**


management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080







